### ISSUE TITLE
Exception when tape is null

### ISSUE THREAD

**Issue by jmelo11** [xcelerit/XAD#54]
Hi to all. I've been thinking of using XAD in a project I'm implementing, and I notice that if a tape is not instantiated and one calls the setDerivative method, the program crashes. Is there a way to prevent the user from doing so? If not, what about doing something like this:

```
XAD_INLINE Scalar& derivative()
    {
        auto t = tape_type::getActive();
        // register ourselves if not already done
        if(!t) throw std::exception("Tape not defined");
        if (slot_ == INVALID_SLOT)
        {
            slot_ = t->registerVariable();
            t->pushLhs(slot_);
        }
        return t->derivative(slot_);
    }
```

What do you think?

Regards,

**Comment by xcelerit-dev** [comment]
Hi @jmelo11. That is indeed a good idea and makes sense at this point, as setting derivatives is typically not performance-critical. Though it would be more suitable to throw a [`NoTapeException`](https://github.com/xcelerit/XAD/blob/main/src/XAD/Exceptions.hpp#L61) in this case.

Could you prepare a pull request for this?

**Comment by jmelo11** [comment]
Ok, I'll look into it!
